### PR TITLE
added package.json, modified on_command_error()

### PR DESCRIPTION
**Pull request by cheeze2000**

### CODE REVIEW

**Comment by Raatty** [comment]
maybe not just delete on command error we might need that for debugging purposes, could maybe change it to send to a separate channel or make debug mode a toggle with a command

**Comment by cheeze2000** [comment]
@Raatty theres nothing much to debug from `on_command_error` apart from a message saying CommandNotFoundError

**Comment by cheeze2000** [comment]
@Raatty edited listener. review requested

**Comment by dustinpianalto** [comment]
@cheeze2000 Can you move `aliases.json` into `shared_libs`, update the urls in `package.json`, move 'package.json', 'package-lock.json`, and `run.js` into the `src` directory, and remove `Async Helper` from the roles that can be self assigned?

**Pull request closed without merging**
