### PR TITLE
Added permunload

### PR DESCRIPTION
**Pull request by davfsa**

### CODE REVIEW

**Comment by davfsa** [comment]
Now it tries to unload the extension and passes if the extension is unloaded

**Comment by neko404notfound** [comment]
I will take your word for it that this works, because I don't have a system working that I can try this out on currently.

@dustinpianalto if anything does break, just need to rollback. I will squash commit so that we can just checkout the old copy if needbe.

**Comment by neko404notfound** [comment]
closes #36 
closes #34

**Comment by neko404notfound** [comment]
closes #36

**Pull request merged**
