### PR TITLE
cogs.txt is useless

### PR DESCRIPTION
**Pull request by yourmothergay**

### CODE REVIEW

**Comment by neko404notfound** [comment]
What if you don't want to load every file?

Might be worth ignoring anything with a `_` at the start? What is everyone elses opinion?

**Comment by davfsa** [comment]
I say we keep cogs.txt like that we can select in what order the cogs get loaded

**Comment by neko404notfound** [comment]
Vote

:+1: to merge, :-1: to retain how it is?

**Comment by sunti21** [comment]
The cogs.txt is a good idea. You can easily choose which cogs should get loaded and which not!

**Comment by Raatty** [comment]
lolz  think this bot the kind of one where we would always want all the cogs loaded

**Comment by neko404notfound** [comment]
@sunti21 @Raatty both good points tbh.

**Comment by davfsa** [comment]
Imagine a cog failed and we had to take it down, we could just remove the name from cogs.txt
In the case we dont have cogs.txt we would have to make many more changes

**Comment by neko404notfound** [comment]
@davfsa that requires either hotswapping that cog file at runtime, or restarting the bot anyway. At which point, currently without something like `systemd` or `forever` running, we would have to SSH into the host for.

<@443708618521444352> / agg (cant mention him :thinking:) made a good point with the load/unload commands.

**Comment by davfsa** [comment]
In that case, we can just use what @yourmothergay said, and if the cog fails, we can do `ds!unload cog`

**Comment by AggPro** [comment]
cogs.txt can be useful for only one thing.

Something like "ds!permunload" can modify the .txt file and remove the certain cog from the loaded list. 

There is a second list that shows the disabled cogs. Through "ds!load" you can select one of these and load it.


I know I haven't explained it right, but at least you understand my point...?

**Comment by davfsa** [comment]
@AggPro I will do it

**Comment by davfsa** [comment]
Shall I make a fork of master of development?

**Comment by neko404notfound** [comment]
Closing.

**Pull request closed without merging**
