### PR TITLE
Added a auto-role event

### PR DESCRIPTION
**Pull request by davfsa**

### CODE REVIEW

**Comment by cheeze2000** [comment]
Nope.

**Comment by dustinpianalto** [comment]
Cheese, this is only for bot accounts.

**Comment by cheeze2000** [comment]
also for bot accounts i made a comment on trello as to how this is deemed as unnecessary at least for me

**Comment by dustinpianalto** [comment]
I agree with your comments. I am going to put this on hold for now.

**Comment by davfsa** [comment]
Im working on a new way of adding bots to the Server, its something like in Plexi Development, what do you guys think?

**Comment by Raatty** [comment]
auto nicknaming sounds good but it will probs be a manual progress actually inviting the bots still

**Comment by davfsa** [comment]
We can just do that when we have time

Btw, I just realiced that that could also help us Keep a list of the developers of the bots and also make the bot developer role automated

**Comment by Raatty** [comment]
that would work I guess

**Comment by davfsa** [comment]
@dustinpianalto what do you think?

**Comment by dustinpianalto** [comment]
Yeah, that is my plan. I need to get the database setup first though.

**Comment by davfsa** [comment]
Till you make the database, I will use a JSON file

**Comment by dustinpianalto** [comment]
@davfsa Can you change this so that, instead of adding a role if a bot joins, it gets added to the database? Just add the bot's ID if it doesn't already exist in the DB, the Owner's ID and Prefix can be blank (just don't put anything in those columns).

**Comment by davfsa** [comment]
@dustinpianalto Im working on a new way to add bots, that will also Change this :)

**Pull request closed without merging**
